Update racks, server pages, add Janet, more info on firewall, etc.
COSI-Lab/book pull request #29
Opened 2024-02-11 20:54 UTC by lavajuno

Lots of changes here:
- Added new left rack
- Updated locations of devices in all racks
- Added page for Janet
- Added trimmed-down example firewall config
- Fix dead link/s to Gitea
- Other small fixes

2024-02-11 21:01 UTC, Warvan1 reviewed
lgtm

2024-02-13 19:16 UTC, carykees98 requested changes

2024-02-13 19:16 UTC, carykees98 commented on src/infrastructure/servers/ziltoid.md
> +_updated: Feb 11, 2023_
```suggestion
_updated: Feb 11, 2024_
```

2024-02-13 19:22 UTC, carykees98 approved these changes
:+1:

2024-02-13 19:43 UTC, Warvan1 approved these changes
lgtm

2024-02-13 22:47 UTC, merged